project:
  type: website

website:
  navbar:
    search: false
    title: false
    left:
      - href: 03_labour_main.qmd
        text: "Canada Employment Tracker"
      - sidebar:how
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  github.com/wvictor14/labourcan
  sidebar:
    - id: how
      title: "How"
      style: "docked"
      contents:
        - 02_develop_visualization.qmd
        - 01_develop_data_processing.qmd